"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _LogReadStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LogReadStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LogReadStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LOG_READ_STATUS_SUCCESS: _LogReadStatus.ValueType  # 0
    LOG_READ_STATUS_UNSPECIFIED: _LogReadStatus.ValueType  # 1
    LOG_READ_STATUS_NOT_FOUND: _LogReadStatus.ValueType  # 2
    LOG_READ_STATUS_TIMEOUT: _LogReadStatus.ValueType  # 3
    LOG_READ_STATUS_GENERIC_ERROR: _LogReadStatus.ValueType  # 6

class LogReadStatus(_LogReadStatus, metaclass=_LogReadStatusEnumTypeWrapper): ...

LOG_READ_STATUS_SUCCESS: LogReadStatus.ValueType  # 0
LOG_READ_STATUS_UNSPECIFIED: LogReadStatus.ValueType  # 1
LOG_READ_STATUS_NOT_FOUND: LogReadStatus.ValueType  # 2
LOG_READ_STATUS_TIMEOUT: LogReadStatus.ValueType  # 3
LOG_READ_STATUS_GENERIC_ERROR: LogReadStatus.ValueType  # 6
Global___LogReadStatus: _TypeAlias = LogReadStatus  # noqa: Y015

@_typing.final
class GetPluginInfoRequest(_message.Message):
    """--- Message Definitions ---"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetPluginInfoRequest: _TypeAlias = GetPluginInfoRequest  # noqa: Y015

@_typing.final
class GetPluginInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    AUTHOR_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    version: _builtins.str
    type: _builtins.str
    author: _builtins.str
    description: _builtins.str
    def __init__(
        self,
        *,
        version: _builtins.str = ...,
        type: _builtins.str = ...,
        author: _builtins.str = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["author", b"author", "description", b"description", "type", b"type", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPluginInfoResponse: _TypeAlias = GetPluginInfoResponse  # noqa: Y015

@_typing.final
class GetAvailableDataPointsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetAvailableDataPointsRequest: _TypeAlias = GetAvailableDataPointsRequest  # noqa: Y015

@_typing.final
class GetAvailableDataPointsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_POINT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def data_point(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        data_point: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_point", b"data_point"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetAvailableDataPointsResponse: _TypeAlias = GetAvailableDataPointsResponse  # noqa: Y015

@_typing.final
class StartLoggingRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StartLoggingRequest: _TypeAlias = StartLoggingRequest  # noqa: Y015

@_typing.final
class StartLoggingResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StartLoggingResponse: _TypeAlias = StartLoggingResponse  # noqa: Y015

@_typing.final
class IsLoggingActiveRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___IsLoggingActiveRequest: _TypeAlias = IsLoggingActiveRequest  # noqa: Y015

@_typing.final
class IsLoggingActiveResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    is_active: _builtins.bool
    def __init__(
        self,
        *,
        is_active: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_active", b"is_active"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IsLoggingActiveResponse: _TypeAlias = IsLoggingActiveResponse  # noqa: Y015

@_typing.final
class StopLoggingRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StopLoggingRequest: _TypeAlias = StopLoggingRequest  # noqa: Y015

@_typing.final
class StopLoggingResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StopLoggingResponse: _TypeAlias = StopLoggingResponse  # noqa: Y015

@_typing.final
class ReadLogRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_POINT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def data_point(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        data_point: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_point", b"data_point"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReadLogRequest: _TypeAlias = ReadLogRequest  # noqa: Y015

@_typing.final
class ReadLogResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___LogResult]: ...
    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___LogResult] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReadLogResponse: _TypeAlias = ReadLogResponse  # noqa: Y015

@_typing.final
class LogResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_POINT_NAME_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: _builtins.int
    data_point_name: _builtins.str
    value: _builtins.int
    status: Global___LogReadStatus.ValueType
    error_message: _builtins.str
    def __init__(
        self,
        *,
        data_point_name: _builtins.str = ...,
        value: _builtins.int = ...,
        status: Global___LogReadStatus.ValueType = ...,
        error_message: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_point_name", b"data_point_name", "error_message", b"error_message", "status", b"status", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogResult: _TypeAlias = LogResult  # noqa: Y015
