# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from logger.v1 import logger_pb2 as logger_dot_v1_dot_logger__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in logger/v1/logger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoggerPluginStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPluginInfo = channel.unary_unary(
                '/logger.v1.LoggerPlugin/GetPluginInfo',
                request_serializer=logger_dot_v1_dot_logger__pb2.GetPluginInfoRequest.SerializeToString,
                response_deserializer=logger_dot_v1_dot_logger__pb2.GetPluginInfoResponse.FromString,
                _registered_method=True)
        self.GetAvailableDataPoints = channel.unary_unary(
                '/logger.v1.LoggerPlugin/GetAvailableDataPoints',
                request_serializer=logger_dot_v1_dot_logger__pb2.GetAvailableDataPointsRequest.SerializeToString,
                response_deserializer=logger_dot_v1_dot_logger__pb2.GetAvailableDataPointsResponse.FromString,
                _registered_method=True)
        self.StartLogging = channel.unary_unary(
                '/logger.v1.LoggerPlugin/StartLogging',
                request_serializer=logger_dot_v1_dot_logger__pb2.StartLoggingRequest.SerializeToString,
                response_deserializer=logger_dot_v1_dot_logger__pb2.StartLoggingResponse.FromString,
                _registered_method=True)
        self.StopLogging = channel.unary_unary(
                '/logger.v1.LoggerPlugin/StopLogging',
                request_serializer=logger_dot_v1_dot_logger__pb2.StopLoggingRequest.SerializeToString,
                response_deserializer=logger_dot_v1_dot_logger__pb2.StopLoggingResponse.FromString,
                _registered_method=True)
        self.ReadLog = channel.unary_unary(
                '/logger.v1.LoggerPlugin/ReadLog',
                request_serializer=logger_dot_v1_dot_logger__pb2.ReadLogRequest.SerializeToString,
                response_deserializer=logger_dot_v1_dot_logger__pb2.ReadLogResponse.FromString,
                _registered_method=True)


class LoggerPluginServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPluginInfo(self, request, context):
        """--- Metadata ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableDataPoints(self, request, context):
        """--- Logging Operations ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartLogging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopLogging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggerPluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPluginInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPluginInfo,
                    request_deserializer=logger_dot_v1_dot_logger__pb2.GetPluginInfoRequest.FromString,
                    response_serializer=logger_dot_v1_dot_logger__pb2.GetPluginInfoResponse.SerializeToString,
            ),
            'GetAvailableDataPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableDataPoints,
                    request_deserializer=logger_dot_v1_dot_logger__pb2.GetAvailableDataPointsRequest.FromString,
                    response_serializer=logger_dot_v1_dot_logger__pb2.GetAvailableDataPointsResponse.SerializeToString,
            ),
            'StartLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.StartLogging,
                    request_deserializer=logger_dot_v1_dot_logger__pb2.StartLoggingRequest.FromString,
                    response_serializer=logger_dot_v1_dot_logger__pb2.StartLoggingResponse.SerializeToString,
            ),
            'StopLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.StopLogging,
                    request_deserializer=logger_dot_v1_dot_logger__pb2.StopLoggingRequest.FromString,
                    response_serializer=logger_dot_v1_dot_logger__pb2.StopLoggingResponse.SerializeToString,
            ),
            'ReadLog': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadLog,
                    request_deserializer=logger_dot_v1_dot_logger__pb2.ReadLogRequest.FromString,
                    response_serializer=logger_dot_v1_dot_logger__pb2.ReadLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logger.v1.LoggerPlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logger.v1.LoggerPlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoggerPlugin(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPluginInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logger.v1.LoggerPlugin/GetPluginInfo',
            logger_dot_v1_dot_logger__pb2.GetPluginInfoRequest.SerializeToString,
            logger_dot_v1_dot_logger__pb2.GetPluginInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableDataPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logger.v1.LoggerPlugin/GetAvailableDataPoints',
            logger_dot_v1_dot_logger__pb2.GetAvailableDataPointsRequest.SerializeToString,
            logger_dot_v1_dot_logger__pb2.GetAvailableDataPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logger.v1.LoggerPlugin/StartLogging',
            logger_dot_v1_dot_logger__pb2.StartLoggingRequest.SerializeToString,
            logger_dot_v1_dot_logger__pb2.StartLoggingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logger.v1.LoggerPlugin/StopLogging',
            logger_dot_v1_dot_logger__pb2.StopLoggingRequest.SerializeToString,
            logger_dot_v1_dot_logger__pb2.StopLoggingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logger.v1.LoggerPlugin/ReadLog',
            logger_dot_v1_dot_logger__pb2.ReadLogRequest.SerializeToString,
            logger_dot_v1_dot_logger__pb2.ReadLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
